title: Triggerende elementen
hero_image: images/banner.png
description: Triggerende elementen
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Triggerende elementen
